spring.application.name=event-ticket-manager

#Database connection
spring.datasource.url= jdbc:postgresql://localhost:5432/postgres

spring.datasource.username=postgres
spring.datasource.password=Sami@khaleel242761

#jpa configuration

# create the schema in the postgres fb based on out jpa entites
#before production you want to stop that and usedb migration tool like flyway
spring.jpa.hibernate.ddl-auto=update 
# printout sql
spring.jpa.show-sql=true
# hibernate technology that works inside the db jpa = implementation of the jpa interface
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


spring.security.oauth2.resourceserver.jwt.issuer-url=http://localhost:9090/realms/event-ticket-platform